В данном ноутбуке мы будем получать через api superjob

In [2]:
%pip install python-dotenv requests

Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests) (2026.2.25)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [87]:
import dotenv
import os

dotenv.load_dotenv(dotenv_path='../../.env')

SUPERJOB_SECRET = os.getenv('SUPERJOB_SECRET_KEY')
SUPERJOB_CLIENT_ID = os.getenv('SUPERJOB_CLIENT_ID')
SUPERJOB_LOGIN = os.getenv('SUPERJOB_LOGIN')
SUPERJOB_PASSWORD = os.getenv('SUPERJOB_PASSWORD')

In [88]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import logging

In [89]:
# Авторизуемся

params = {
    'client_id': SUPERJOB_CLIENT_ID,
    'client_secret': SUPERJOB_SECRET,
    'login': SUPERJOB_LOGIN,
    'password': SUPERJOB_PASSWORD,
}

auth_response = requests.post('https://api.superjob.ru/2.0/oauth2/password/', params=params)

In [90]:
token = auth_response.json()['access_token']
headers = {
    "Authorization": f"Bearer {token}",
    "X-Api-App-Id": SUPERJOB_SECRET
}

In [91]:
industry = requests.get('https://api.superjob.ru/2.0/catalogues/', headers=headers)
industry_res = industry.json()
industry_res[0]

{'title_rus': 'IT, Интернет, связь, телеком',
 'url_rus': 'it-internet-svyaz-telekom',
 'title': 'IT, Интернет, связь, телеком',
 'title_trimmed': 'IT, Интернет, связь,...',
 'key': 33,
 'positions': [{'title_rus': 'AI',
   'url_rus': 'ai',
   'title': 'AI',
   'id_parent': 33,
   'key': 651},
  {'title_rus': 'CRM-системы',
   'url_rus': 'crm-sistemy',
   'title': 'CRM-системы',
   'id_parent': 33,
   'key': 603},
  {'title_rus': 'Data Science',
   'url_rus': 'data-science',
   'title': 'Data Science',
   'id_parent': 33,
   'key': 627},
  {'title_rus': 'DevOps',
   'url_rus': 'devops',
   'title': 'DevOps',
   'id_parent': 33,
   'key': 628},
  {'title_rus': 'SRE',
   'url_rus': 'sre',
   'title': 'SRE',
   'id_parent': 33,
   'key': 629},
  {'title_rus': 'Web-верстка',
   'url_rus': 'web-verstka',
   'title': 'Web-верстка',
   'id_parent': 33,
   'key': 36},
  {'title_rus': 'Администрирование баз данных',
   'url_rus': 'administrirovanie-baz-dannyh',
   'title': 'Администрирование баз данных',
   'id_parent': 33,
   'key': 37},
  {'title_rus': 'Аналитика',
   'url_rus': 'analitika',
   'title': 'Аналитика',
   'id_parent': 33,
   'key': 38},
  {'title_rus': 'Внедрение и сопровождение ПО',
   'url_rus': 'vnedrenie-po',
   'title': 'Внедрение и сопровождение ПО',
   'id_parent': 33,
   'key': 503},
  {'title_rus': 'Игровое ПО / Геймдев',
   'url_rus': 'igrovoe-po',
   'title': 'Игровое ПО / Геймдев',
   'id_parent': 33,
   'key': 40},
  {'title_rus': 'Инжиниринг',
   'url_rus': 'inzhiniring',
   'title': 'Инжиниринг',
   'id_parent': 33,
   'key': 41},
  {'title_rus': 'Интернет, создание и поддержка сайтов',
   'url_rus': 'internet-sozdanie-i-podderzhka-sajtov',
   'title': 'Интернет, создание и поддержка сайтов',
   'id_parent': 33,
   'key': 42},
  {'title_rus': 'Информационная безопасность',
   'url_rus': 'informacionnaya-bezopasnost',
   'title': 'Информационная безопасность',
   'id_parent': 33,
   'key': 546},
  {'title_rus': 'Киберспорт',
   'url_rus': 'cybersport',
   'title': 'Киберспорт',
   'id_parent': 33,
   'key': 620},
  {'title_rus': 'Компьютерная анимация\xa0и\xa0мультимедиа',
   'url_rus': 'kompyuternaya-animaciya-i-multimedia',
   'title': 'Компьютерная анимация\xa0и\xa0мультимедиа',
   'id_parent': 33,
   'key': 43},
  {'title_rus': 'Контент',
   'url_rus': 'kontent',
   'title': 'Контент',
   'id_parent': 33,
   'key': 44},
  {'title_rus': 'Мобильная разработка',
   'url_rus': 'mobilnaya-razrabotka',
   'title': 'Мобильная разработка',
   'id_parent': 33,
   'key': 604},
  {'title_rus': 'Нейросети / Искусственный интеллект',
   'url_rus': 'nejroseti-i-iskusstvennyj-intellekt',
   'title': 'Нейросети / Искусственный интеллект',
   'id_parent': 33,
   'key': 650},
  {'title_rus': 'Оптимизация, SEO',
   'url_rus': 'optimizaciya-seo',
   'title': 'Оптимизация, SEO',
   'id_parent': 33,
   'key': 45},
  {'title_rus': 'Передача данных и доступ в интернет',
   'url_rus': 'peredacha-dannyh-i-dostup-v-internet',
   'title': 'Передача данных и доступ в интернет',
   'id_parent': 33,
   'key': 46},
  {'title_rus': 'Разработка и сопровождение банковского ПО',
   'url_rus': 'razrabotka-i-soprovozhdenie-bankovskogo-po',
   'title': 'Разработка и сопровождение банковского ПО',
   'id_parent': 33,
   'key': 47},
  {'title_rus': 'Разработка, программирование',
   'url_rus': 'razrabotka-po',
   'title': 'Разработка, программирование',
   'id_parent': 33,
   'key': 48},
  {'title_rus': 'Сетевые технологии',
   'url_rus': 'setevye-tehnologii',
   'title': 'Сетевые технологии',
   'id_parent': 33,
   'key': 49},
  {'title_rus': 'Системная интеграция',
   'url_rus': 'sistemnaya-integraciya',
   'title': 'Системная интеграция',
   'id_parent': 33,
   'key': 50},
  {'title_rus': 'Системное администрирование',
   'url_rus': 'sistemnoe-administrirovanie',
   'title': 'Системное администрирование',
   'id_parent': 33,
   'key': 51},
  {'title_rus': 'Системы автоматизированного проектирования (САПР)',
   'url_rus': 'sistemy-avtomatizirovannogo-proektirovaniya-sapr',
   'title': 'Системы автоматизированного проектирования (САПР)',
   'id_parent': 33,
   'key': 52},
  {'title_rus': 'Системы управления предприятием (ERP)',
   'url_rus': 'sistemy-upravleniya-predpriyatiem-erp',
   'title': 'Системы управления предприятием (ERP)',
   'id_parent': 33,
   'key': 53},
  {'title_rus': 'Сотовые, беспроводные технологии',
   'url_rus': 'sotovye-besprovodnye-tehnologii',
   'title': 'Сотовые, беспроводные технологии',
   'id_parent': 33,
   'key': 54},
  {'title_rus': 'Телекоммуникации и связь',
   'url_rus': 'telekommunikacii-i-svyaz',
   'title': 'Телекоммуникации и связь',
   'id_parent': 33,
   'key': 55},
  {'title_rus': 'Тестирование, QA',
   'url_rus': 'testirovanie',
   'title': 'Тестирование, QA',
   'id_parent': 33,
   'key': 56},
  {'title_rus': 'Техническая документация',
   'url_rus': 'tehnicheskaja-dokumentacija',
   'title': 'Техническая документация',
   'id_parent': 33,
   'key': 614},
  {'title_rus': 'Техническая поддержка',
   'url_rus': 'tehnicheskaya-podderzhka',
   'title': 'Техническая поддержка',
   'id_parent': 33,
   'key': 57},
  {'title_rus': 'Управление продуктом',
   'url_rus': 'upravlenie-produktom',
   'title': 'Управление продуктом',
   'id_parent': 33,
   'key': 613},
  {'title_rus': 'Управление проектами',
   'url_rus': 'upravlenie-proektami',
   'title': 'Управление проектами',
   'id_parent': 33,
   'key': 605},
  {'title_rus': 'Управление разработкой',
   'url_rus': 'upravlenie-razrabotkoj',
   'title': 'Управление разработкой',
   'id_parent': 33,
   'key': 630},
  {'title_rus': 'Юзабилити',
   'url_rus': 'yuzabiliti',
   'title': 'Юзабилити',
   'id_parent': 33,
   'key': 59},
  {'title_rus': 'Другое',
   'url_rus': 'drugoe',
   'title': 'Другое',
   'id_parent': 33,
   'key': 60},
  {'title_rus': 'Начало карьеры, мало опыта',
   'url_rus': 'nachalo-karery-malo-opyta',
   'title': 'Начало карьеры, мало опыта',
   'id_parent': 33,
   'key': 61}]}

Здесь сразу можно отметить, что 'IT, Интернет, связь, телеком' - первая отрасль и  ее 'key': 33

In [92]:
titles = []
for catalogue in industry_res:
    titles.append(catalogue['title_rus'])
print(titles)

['IT, Интернет, связь, телеком', 'Административная работа, секретариат, АХО', 'Банки, инвестиции, лизинг', 'Безопасность, службы охраны', 'Бухгалтерия, финансы, аудит', 'Государственная служба', 'Дизайн', 'Домашний персонал', 'Закупки, снабжение', 'Искусство, культура, развлечения', 'Кадры, управление персоналом', 'Консалтинг, стратегическое развитие', 'Маркетинг, реклама, PR', 'Медицина, фармацевтика, ветеринария', 'Наука, образование, повышение квалификации', 'Некоммерческие организации, волонтерство', 'Обмен персоналом', 'Продажи', 'Промышленность, производство', 'Рабочий персонал', 'Сельское хозяйство', 'Службы доставки', 'СМИ, издательства', 'Спорт, фитнес, салоны красоты, SPA', 'Страхование', 'Строительство, проектирование, недвижимость', 'Сырье', 'Топ-персонал', 'Транспорт, логистика, ВЭД', 'Туризм, гостиницы, общественное питание', 'Услуги, ремонт, сервисное обслуживание', 'Юриспруденция']

Список отраслей: ['IT, Интернет, связь, телеком', 'Административная работа, секретариат, АХО', 'Банки, инвестиции, лизинг', 'Безопасность, службы охраны', 'Бухгалтерия, финансы, аудит', 'Государственная служба', 'Дизайн', 'Домашний персонал', 'Закупки, снабжение', 'Искусство, культура, развлечения', 'Кадры, управление персоналом', 'Консалтинг, стратегическое развитие', 'Маркетинг, реклама, PR', 'Медицина, фармацевтика, ветеринария', 'Наука, образование, повышение квалификации', 'Некоммерческие организации, волонтерство', 'Обмен персоналом', 'Продажи', 'Промышленность, производство', 'Рабочий персонал', 'Сельское хозяйство', 'Службы доставки', 'СМИ, издательства', 'Спорт, фитнес, салоны красоты, SPA', 'Страхование', 'Строительство, проектирование, недвижимость', 'Сырье', 'Топ-персонал', 'Транспорт, логистика, ВЭД', 'Туризм, гостиницы, общественное питание', 'Услуги, ремонт, сервисное обслуживание', 'Юриспруденция']

Тк мы рассматриваем сферу  it, то нам подойдет отрасль 'IT, Интернет, связь, телеком'. Однако также есть отрасль 'Дизайн'. UX/UI дизайнеры и исследователи тоже относятся к ИТ-профессиям. Надо проверить, возможно, эти ИТ-направления относятся к данной отрасли, а не к 'IT, Интернет, связь, телеком'.

In [93]:
titles_in_design = []
for position in  industry_res[6]['positions']:
    titles_in_design.append(position['title_rus'])
print(titles_in_design)

['Web-дизайн (UI/UX)', 'Архитектура', 'Аудио / Саунд-дизайн', 'Верстка и полиграфия', 'Видео, CGI, анимация', 'Графический дизайн', 'Дизайн интерьера', 'Иллюстрации', 'Ландшафтный дизайн', 'Мода\xa0и\xa0Аксессуары', 'Промышленный дизайн', 'Рекламный дизайн / Ивенты, инсталляции, стенды', 'Фотография', 'Другое', 'Начало карьеры, мало опыта']

И правда - из всех направлений дизайна также подходит направление 'Web-дизайн (UI/UX)' как часть IT-сферы.

In [94]:
industry_res[6]['positions'][0]

{'title_rus': 'Web-дизайн (UI/UX)',
 'url_rus': 'web-dizajn',
 'title': 'Web-дизайн (UI/UX)',
 'id_parent': 62,
 'key': 35}

In [ ]:
# Получаем список вакансий по веб-дизигну с помощью key=35

params = {
    'catalogues': 35,
}

vacs_design = requests.get('https://api.superjob.ru/2.0/vacancies/', headers=headers, params=params)
design_res = vacs_design.json()
design_res['total']

43

по 40 вакансий на page => 2 pages надо пройти чтобы скачать всё в один датафрейм

In [111]:
res_vacs_design = []
params = {
    'catalogues': 35,
    'count': 40,
    'page': 0
}

for page in range(2):
    params['page']=page
    vacs_design = requests.get('https://api.superjob.ru/2.0/vacancies/', headers=headers, params=params)
    vacs_design_json = vacs_design.json()
    res_vacs_design.extend(vacs_design_json['objects'])
    
df_design_vacs=pd.DataFrame(res_vacs_design)
df_design_vacs

,contacts_hidden,contact_hiding_cause,canEdit,is_closed,id,id_client,payment_from,payment_to,date_pub_to,date_archived,...,highlight,age_from,age_to,gender,firm_name,firm_activity,link,isBlacklisted,latitude,longitude
0,True,no_resume,False,False,50780033,14215,31500,32000,1775822012,1771476907,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Почта России,Почта России сейчас — это важная часть социаль...,https://bizhbulyak.superjob.ru/vakansii/operat...,False,53.698341,54.268978
1,True,no_resume,False,False,51646102,4944790,0,0,1777646146,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Лаборатория Касперского,Обязанности:Требования:Условия.,https://www.superjob.ru/vakansii/ux-51646102.html,False,NaN,NaN
2,True,no_resume,False,False,51697899,11714,92000,105000,1777802103,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://www.superjob.ru/vakansii/ux-issledovat...,False,55.764221,37.617321
3,True,no_resume,False,False,51697901,11714,60000,80000,1777802103,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://www.superjob.ru/vakansii/ux-issledovat...,False,55.764221,37.617321
4,True,no_resume,False,False,51720163,4952362,0,0,1775902509,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Магнит: Старт Карьеры,Обязанности:Требования:Условия.,https://www.superjob.ru/vakansii/kommunikacion...,False,NaN,NaN
5,True,no_resume,False,False,51742606,4954737,0,0,1776769821,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",SKIMS,Обязанности:Требования:Условия.,https://www.superjob.ru/vakansii/dizajner-5174...,False,NaN,NaN
6,True,no_resume,False,False,51782102,2466656,58000,0,1775897834,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}","ОАО ""РЖД""",ПЕРЕВОЗКА ГРУЗОВ И ПАССАЖИРОВ,https://ryazan.superjob.ru/vakansii/brigadir-5...,False,54.631798,39.717808
7,True,no_resume,False,False,51826693,4959764,0,0,1776933780,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Amazon,Обязанности:Требования:Условия.,https://www.superjob.ru/vakansii/stazhjor-ux-d...,False,NaN,NaN
8,True,no_resume,False,False,51836446,14215,31500,32000,1777188133,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Почта России,Почта России сейчас — это важная часть социаль...,https://buraevo.superjob.ru/vakansii/operator-...,False,55.842308,55.404297
9,True,no_resume,False,False,51853120,4957734,0,0,1777804260,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Disney,Обязанности:Требования:Условия.,https://www.superjob.ru/vakansii/stazher-otdel...,False,NaN,NaN
10,True,no_resume,False,False,51862377,0,70000,160000,1778138878,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Тануки,Доход 70 000–160 000 ₽ в месяц (в среднем 130 ...,https://www.superjob.ru/vakansii/avtokurer-na-...,False,55.774109,37.398762
11,True,no_resume,False,False,51867220,4962144,0,0,1778229720,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Пятница,Обязанности:Требования:Условия.,https://www.superjob.ru/vakansii/brodkast-diza...,False,NaN,NaN
12,True,no_resume,False,False,51868902,0,70000,160000,1778264916,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Тануки,Доход 70 000–160 000 ₽ в месяц (в среднем 130 ...,https://www.superjob.ru/vakansii/avtokurer-na-...,False,55.988918,37.155361
13,True,no_resume,False,False,51297887,4262900,57472,0,1775829916,1765637402,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Гражданстрой,Компания осуществляет промышленно-гражданское ...,https://smolensk.superjob.ru/vakansii/dizajner...,False,54.769077,32.067429
14,True,no_resume,False,False,51703169,75401,68000,75000,1777910405,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}","""БЭСТ ПРАЙС"" / Fix Price",Торговая сеть Fix Price – уникальный проект на...,https://www.superjob.ru/vakansii/kassir-torgov...,False,55.731712,37.730591
15,True,no_resume,False,False,51719668,100593,0,0,1777014158,1773303902,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",М. Видео-Эльдорадо,Группа «М. Видео-Эльдорадо» — лидер среди розн...,https://www.superjob.ru/vakansii/dizajner-vers...,False,55.699001,37.343029
16,True,no_resume,False,False,51740496,291920,50000,70000,1776696304,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ФГБОУ ВО Санкт-Петербургский государственный у...,Санкт-Петербургский государственный университе...,https://spb.superjob.ru/vakansii/dizajner-cent...,False,59.942223,30.274572
17,True,no_resume,False,False,51779814,280168,37000,48300,1775806930,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://cheboksary.superjob.ru/vakansii/prodav...,False,56.140163,47.283165
18,True,no_resume,False,False,51780107,280168,53400,63400,1775810392,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://ramenskoe.superjob.ru/vakansii/adminis...,False,55.485203,37.977051
19,True,no_resume,False,False,51781506,280168,63200,90500,1775890687,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://spb.superjob.ru/vakansii/prodavec-maga...,False,59.929710,30.420118
20,True,no_resume,False,False,51781566,280168,36300,48000,1775891162,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://stroitel.superjob.ru/vakansii/prodavec...,False,50.779263,36.503895
21,True,no_resume,False,False,51781996,280168,67100,89400,1775894746,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://www.superjob.ru/vakansii/prodavec-maga...,False,55.695377,37.574146
22,True,no_resume,False,False,51800188,4236166,75000,0,1776494601,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","АНО ДПО ""АДПО""",Академия дополнительного профессионального обр...,https://spb.superjob.ru/vakansii/organizator-p...,False,60.050915,30.382380
23,True,no_resume,False,False,51801101,14215,0,0,1776506043,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Почта России,Почта России сейчас — это важная часть социаль...,https://izobilnyj.superjob.ru/vakansii/operato...,False,45.263187,41.843391
24,True,no_resume,False,False,51801620,100593,44000,50000,1776520782,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",М.Видео-Эльдорадо,Группа «М. Видео-Эльдорадо» — лидер среди розн...,https://spb.superjob.ru/vakansii/prodavec-tehn...,False,59.911114,30.445738
25,True,no_resume,False,False,51809044,291920,60000,0,1776586961,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ФГБОУ ВО Санкт-Петербургский государственный у...,Санкт-Петербургский государственный университе...,https://spb.superjob.ru/vakansii/dizajner-vers...,False,59.943085,30.278831
26,True,no_resume,False,False,51821480,280168,37000,49500,1776717675,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://ufa.superjob.ru/vakansii/prodavec-v-zo...,False,54.767170,56.080502
27,True,no_resume,False,False,51830224,0,60000,0,1777017535,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Маркетинг и продажи,Маркетинг и продажи,https://www.superjob.ru/vakansii/menedzher-so-...,False,NaN,NaN
28,True,no_resume,False,False,51842330,14215,52500,61000,1777446415,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Почта России,Почта России сейчас — это важная часть социаль...,https://www.superjob.ru/vakansii/operator-po-r...,False,NaN,NaN
29,True,no_resume,False,False,51844028,100593,55000,83000,1777469316,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",М.Видео-Эльдорадо,Группа «М. Видео-Эльдорадо» — лидер среди розн...,https://spb.superjob.ru/vakansii/prodavec-kons...,False,60.049198,30.444614
30,True,no_resume,False,False,51845967,248733,100000,120000,1777554976,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнолия, Сеть магазинов",«Магнолия» - это сеть удобных магазинов с ассо...,https://www.superjob.ru/vakansii/administrator...,False,55.677654,37.659821
31,True,no_resume,False,False,51846784,280168,28500,34400,1777618252,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://tatishchevo.superjob.ru/vakansii/proda...,False,51.665623,45.581982
32,True,no_resume,False,False,51846894,280168,54300,75400,1777619202,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://podolsk.superjob.ru/vakansii/prodavec-...,False,55.439243,37.566349
33,True,no_resume,False,False,51847024,280168,42100,50000,1777620437,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://lyubertsy.superjob.ru/vakansii/prodave...,False,55.674442,37.875011
34,True,no_resume,False,False,51858239,280168,44800,59700,1778024425,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://petrozavodsk.superjob.ru/vakansii/prod...,False,61.810486,34.322235
35,True,no_resume,False,False,51858977,280168,0,0,1778049721,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://kotelniki.superjob.ru/vakansii/prodave...,False,55.662151,37.856083
36,True,no_resume,False,False,51800801,15563,0,120000,1776500220,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Henderson,Дом моды HENDERSON более 20 лет предлагает муж...,https://www.superjob.ru/vakansii/retusher-diza...,False,55.903893,37.427113
37,True,no_resume,False,False,51864555,280168,33900,45100,1778157527,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://kirov-kaluga.superjob.ru/vakansii/prod...,False,54.079227,34.306839
38,True,no_resume,False,False,51867914,75401,68000,75000,1778236194,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}",FIX PRICE,Торговая сеть Fix Price – уникальный проект на...,https://www.superjob.ru/vakansii/merchandajzer...,False,55.856281,37.478729
39,True,no_resume,False,False,51868674,280168,40000,58500,1778247429,0,...,False,0,0,"{'id': 0, 'title': 'Не имеет значения'}","Магнит, Розничная сеть","Мы растём и меняемся уже много лет, становимся...",https://perm.superjob.ru/vakansii/prodavec-v-z...,False,58.051003,56.089558
40,True,no_resume,False,False,51692428,75401,68000,75000,1777794440,1775123402,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}","""БЭСТ ПРАЙС"" / Fix Price",Торговая сеть Fix Price – уникальный проект на...,https://www.superjob.ru/vakansii/prodavec-kass...,False,55.863304,37.591091
41,True,no_resume,False,False,51702654,75401,75500,82500,1777908004,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}","""БЭСТ ПРАЙС"" / Fix Price",Торговая сеть Fix Price – уникальный проект на...,https://www.superjob.ru/vakansii/starshij-prod...,False,55.659649,37.750740
42,True,no_resume,False,False,51700730,75401,68000,75000,1777904406,0,...,True,0,0,"{'id': 0, 'title': 'Не имеет значения'}","""БЭСТ ПРАЙС"" / Fix Price",Торговая сеть Fix Price – уникальный проект на...,https://www.superjob.ru/vakansii/prodavec-5170...,False,55.660225,37.515144

In [ ]:
key_it = 33

res_vacs_it = []
params = {
    'catalogues': key_it,
    'count': 40,
    'page': 0
}
while True:
    
    vacs_it = requests.get('https://api.superjob.ru/2.0/vacancies/', headers=headers, params=params)
    if vacs_it.status_code != 200:
        break
    vacs_it_json = vacs_it.json()

    if not vacs_it_json['objects']:
        break
    res_vacs_it.extend(vacs_it_json['objects'])
    params['page'] += 1

(Источник, где я смотрела способ сбора данных со всех страниц: https://sky.pro/wiki/media/kak-ispolzovat-python-dlya-raboty-s-rest-api/)

In [290]:
df_it = pd.DataFrame(res_vacs_it)
df_it

,contacts_hidden,contact_hiding_cause,canEdit,is_closed,id,id_client,payment_from,payment_to,date_pub_to,date_archived,...,age_from,age_to,gender,firm_name,firm_activity,link,isBlacklisted,latitude,longitude,video
0,True,no_resume,False,False,51697590,11714,0,0,1777812604,1772612101,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://ufa.superjob.ru/vakansii/dezhurnyj-spe...,False,54.783783,56.122543,NaN
1,True,no_resume,False,False,51697719,11714,0,36540,1777799110,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://furmanov.superjob.ru/vakansii/sistemny...,False,57.257141,41.117516,NaN
2,True,no_resume,False,False,51697696,11714,50000,60000,1777798205,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://www.superjob.ru/vakansii/sistemnyj-adm...,False,46.114944,32.907536,NaN
3,True,no_resume,False,False,51697700,11714,30450,56550,1777798503,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://tosno.superjob.ru/vakansii/sistemnyj-a...,False,59.537891,30.883648,NaN
4,True,no_resume,False,False,51697714,11714,30000,35000,1777799109,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",Филиал ФКУ Налог-Сервис ФНС России по ЦОД в г....,"Федеральный казённое учреждение, подведомствен...",https://www.superjob.ru/vakansii/sistemnyj-adm...,False,46.114944,32.907536,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,True,no_resume,False,False,51863523,4961470,200000,0,1778151277,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ПСМ,"Корпорация, целью которой является оптимизация...",https://yakutsk.superjob.ru/vakansii/veduschij...,False,NaN,NaN,NaN
516,True,no_resume,False,False,51863524,4961470,200000,0,1778151277,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ПСМ,"Корпорация, целью которой является оптимизация...",https://arsenev.superjob.ru/vakansii/veduschij...,False,NaN,NaN,NaN
517,True,no_resume,False,False,51863525,4961470,200000,0,1778151277,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ПСМ,"Корпорация, целью которой является оптимизация...",https://artem.superjob.ru/vakansii/veduschij-i...,False,NaN,NaN,NaN
518,True,no_resume,False,False,51863526,4961470,200000,0,1778151277,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ПСМ,"Корпорация, целью которой является оптимизация...",https://bolshoj-kamen.superjob.ru/vakansii/ved...,False,NaN,NaN,NaN
519,True,no_resume,False,False,51866056,3940185,68000,90000,1778203683,0,...,0,0,"{'id': 0, 'title': 'Не имеет значения'}",ЦЭНКИ,АО «Центр эксплуатации объектов наземной косми...,https://blagoveshensk.superjob.ru/vakansii/teh...,False,NaN,NaN,NaN

Так как выбранная отрасль - 'IT, Интернет, связь, телеком' содержит не только ИТ сферу, но и работу со связью и телекомом, то стоит подробнее рассмотреть, что необходимо исключить из выборки.

In [289]:
titles_in_it_industry = []
for position in  industry_res[0]['positions']:
    titles_in_it_industry.append(position['title_rus'])
print(titles_in_it_industry)

['AI', 'CRM-системы', 'Data Science', 'DevOps', 'SRE', 'Web-верстка', 'Администрирование баз данных', 'Аналитика', 'Внедрение и сопровождение ПО', 'Игровое ПО / Геймдев', 'Инжиниринг', 'Интернет, создание и поддержка сайтов', 'Информационная безопасность', 'Киберспорт', 'Компьютерная анимация\xa0и\xa0мультимедиа', 'Контент', 'Мобильная разработка', 'Нейросети / Искусственный интеллект', 'Оптимизация, SEO', 'Передача данных и доступ в интернет', 'Разработка и сопровождение банковского ПО', 'Разработка, программирование', 'Сетевые технологии', 'Системная интеграция', 'Системное администрирование', 'Системы автоматизированного проектирования (САПР)', 'Системы управления предприятием (ERP)', 'Сотовые, беспроводные технологии', 'Телекоммуникации и связь', 'Тестирование, QA', 'Техническая документация', 'Техническая поддержка', 'Управление продуктом', 'Управление проектами', 'Управление разработкой', 'Юзабилити', 'Другое', 'Начало карьеры, мало опыта']

Список специализаций отрасли: ['AI', 'CRM-системы', 'Data Science', 'DevOps', 'SRE', 'Web-верстка', 'Администрирование баз данных', 'Аналитика', 'Внедрение и сопровождение ПО', 'Игровое ПО / Геймдев', 'Инжиниринг', 'Интернет, создание и поддержка сайтов', 'Информационная безопасность', 'Киберспорт', 'Компьютерная анимация\xa0и\xa0мультимедиа', 'Контент', 'Мобильная разработка', 'Нейросети / Искусственный интеллект', 'Оптимизация, SEO', 'Передача данных и доступ в интернет', 'Разработка и сопровождение банковского ПО', 'Разработка, программирование', 'Сетевые технологии', 'Системная интеграция', 'Системное администрирование', 'Системы автоматизированного проектирования (САПР)', 'Системы управления предприятием (ERP)', 'Сотовые, беспроводные технологии', 'Телекоммуникации и связь', 'Тестирование, QA', 'Техническая документация', 'Техническая поддержка', 'Управление продуктом', 'Управление проектами', 'Управление разработкой', 'Юзабилити', 'Другое', 'Начало карьеры, мало опыта'].
Здесь нам точно не подойдут: 'Телекоммуникации и связь', 'Техническая поддержка'

Уберем из датафрейма вакансии, которые относятся к этим специализациям

In [301]:
def del_vacs(catalogues, list_specialization):
    for cat in catalogues:
        for pos in cat['positions']:
            if pos['title'] in list_specialization:
                return True
    return False
            
list_specialization = ['Телекоммуникации и связь', 'Телекоммуникации и связь']
mask_del = df_it['catalogues'].apply(lambda x: del_vacs(x, list_specialization))

df_it_right = df_it[~mask_del]
len(df_it_right)

466

После удаления неподходящих специализаций осталось 466 строк.

In [ ]:
params = {
    'keyword': 'IT'
}

vacs = requests.get('https://api.superjob.ru/2.0/vacancies/', headers=headers, params=params)
res = vacs.json()

res.keys()

dict_keys(['objects', 'total', 'more', 'subscription_id', 'subscription_active'])