In [69]:
%pip install spacy

Collecting spacy
  Downloading spacy-3.8.14-cp313-cp313-macosx_11_0_arm64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.7 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (14 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (2.11.7)
Requirement already satisfied: jinja2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (7.5 kB)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: httpx>=0.24.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.7.0)
Requirement already satisfied: httpcore==1.* in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: wrapt in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from jinja2->spacy) (3.0.2)
Downloading spacy-3.8.14-cp313-cp313-macosx_11_0_arm64.whl (6.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 20.0 MB/s eta 0:00:00MB/s eta 0:00:01
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp313-cp313-macosx_11_0_arm64.whl (42 kB)
Downloading murmurhash-1.0.15-cp313-cp313-macosx_11_0_arm64.whl (27 kB)
Downloading preshed-3.0.13-cp313-cp313-macosx_11_0_arm64.whl (136 kB)
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp313-cp313-macosx_11_0_arm64.whl (656 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 656.7/656.7 kB 2.3 MB/s eta 0:00:00
Downloading thinc-8.3.13-cp313-cp313-macosx_11_0_arm64.whl (788 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.1/788.1 kB 25.1 MB/s eta 0:00:00
Downloading blis-1.3.3-cp313-cp313-macosx_11_0_arm64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 23.2 MB/s eta 0:00:00
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-1.0.0-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Downloading smart_open-7.5.1-py3-none-any.whl (64 kB)
Installing collected packages: wasabi, spacy-loggers, spacy-legacy, smart-open, murmurhash, cymem, confection, cloudpathlib, catalogue, blis, srsly, preshed, weasel, thinc, spacy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [spacy]m━━ 14/15 [spacy][thinc]
Successfully installed blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.23.0 confection-1.3.3 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.13 smart-open-7.5.1 spacy-3.8.14 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.3 thinc-8.3.13 wasabi-1.1.3 weasel-1.0.0
Note: you may need to restart the kernel to use updated packages.

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import spacy
from spacy.matcher import PhraseMatcher

In [60]:
df = pd.read_csv('df_hh.csv')
df

,title,hh_link,address,company,short_description,experience,salary
0,Разработчик,https://hh.ru/vacancy/131819443?query=%D1%80%D...,Москва,"Русская Медиагруппа, радиохолдинг",Опыт работы,Опыт 3-6 лет,NaN
1,Разработчик,https://hh.ru/vacancy/131986214?query=%D1%80%D...,Москва,Детский хоспис Дом с маяком,"Уверенное знание Python 3, базовых принципов О...",Опыт 1-3 года,"от 95 000 ₽ за месяц, на руки"
2,Backend-разработчик,https://hh.ru/vacancy/131274910?query=%D1%80%D...,Москва,ООО ГК СтиС,2+ года коммерческой разработки на PHP 7.4+. У...,Опыт 1-3 года,NaN
3,Разработчик ЦФТ,https://hh.ru/vacancy/132003073?query=%D1%80%D...,Москва,Bell Integrator,Опыт работы с АБС «ЦФТ-Банк» в качестве,Опыт 3-6 лет,NaN
4,Разработчик C++,https://hh.ru/vacancy/132001730?query=%D1%80%D...,Москва,ООО БУЛАТ,Опыт разработки или исправления/доработки внут...,Опыт 3-6 лет,NaN
...,...,...,...,...,...,...,...
13546,Бизнес-аналитик / Системный аналитик (Fullstac...,https://hh.ru/vacancy/131129287?query=%D0%BF%D...,Санкт-Петербург,ООО Апартмент системс,Опыт работы бизнес-аналитиком / системным анал...,Опыт 3-6 лет,NaN
13547,Девелопер обуви и аксессуаров,https://hh.ru/vacancy/131335836?query=%D0%BF%D...,"Москва, р-н Преображенское",Ushatava,"Аналогичный опыт работы от 3 лет, опыт работы",Опыт 1-3 года,NaN
13548,Product Analyst,https://hh.ru/vacancy/131303603?query=%D0%BF%D...,"Москва, р-н Раменки",Clear Mind,Опытом самостоятельного создания воронок и фор...,Опыт 3-6 лет,NaN
13549,Начальник отдела маркетинга,https://hh.ru/vacancy/128851476?query=%D0%BF%D...,"Челябинск, р-н Центральный",ООО Чебаркульская птица,"Опыт работы в маркетинге от 3 лет, из них не м...",Опыт 3-6 лет,NaN
13550,Продуктовый маркетолог,https://hh.ru/vacancy/131156374?query=%D0%BF%D...,Москва,"""МТС"", Маркетинг и PR","Опыт работы с CJ, вовлекающими механиками, ист...",Опыт 3-6 лет,NaN

In [61]:
df.describe()

,title,hh_link,address,company,short_description,experience,salary
count,13551,13551,13550,13550,13413,13550,3409
unique,7981,12135,1549,6170,10192,4,1072
top,Инженер по качеству,https://hh.ru/vacancy/131918299?query=it&hhtmF...,Москва,Сбер. IT,Опыт работы,Опыт 1-3 года,"от 100 000 ₽ за месяц, на руки"
freq,191,3,6492,360,183,6005,107

In [62]:
# очищаем дубли

df = df.drop_duplicates()
len(df)

12136

In [65]:
# Поработаем с графой опыта

df['short_description']

0                                              Опыт работы
1        Уверенное знание Python 3, базовых принципов О...
2        2+ года коммерческой разработки на PHP 7.4+. У...
3                  Опыт работы с АБС «ЦФТ-Банк» в качестве
4        Опыт разработки или исправления/доработки внут...
                               ...
13546    Опыт работы бизнес-аналитиком / системным анал...
13547        Аналогичный опыт работы от 3 лет, опыт работы
13548    Опытом самостоятельного создания воронок и фор...
13549    Опыт работы в маркетинге от 3 лет, из них не м...
13550    Опыт работы с CJ, вовлекающими механиками, ист...
Name: short_description, Length: 12136, dtype: object

Нам нужно достать навыки из описания вакансии

Нашел [гитхаб](https://github.com/iconicompany/iskillmatching) человечка, который уже решал такую проблему. Адаптируем такое решение

Пайплайн будет следующий:
1. Извлекаем по шаблонам навыки
2. Нормализуем навыки для удобного анализа. Например Python3 -> Python

In [ ]:
# очень удобно воруем) 

skills = pd.read_csv('skills.csv') 
skills

             Название
0                *nix
1                   -
2                .NET
3              .NET 3
4            .net 3,5
...               ...
15854     Яндекс.Вики
15855    Яндекс.Касса
15856  Яндекс.Метрика
15857   Яндекс.Трекер
15858          №63-ФЗ

[15859 rows x 1 columns]

In [74]:
spacy.cli.download("ru_core_news_sm")

Collecting ru-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ru_core_news_sm-3.8.0/ru_core_news_sm-3.8.0-py3-none-any.whl (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 25.7 MB/s eta 0:00:00 MB/s eta 0:00:0101
Collecting pymorphy3>=1.0.0 (from ru-core-news-sm==3.8.0)
  Downloading pymorphy3-2.0.6-py3-none-any.whl.metadata (2.4 kB)
Collecting dawg2-python>=0.8.0 (from pymorphy3>=1.0.0->ru-core-news-sm==3.8.0)
  Downloading dawg2_python-0.9.0-py3-none-any.whl.metadata (7.5 kB)
Collecting pymorphy3-dicts-ru (from pymorphy3>=1.0.0->ru-core-news-sm==3.8.0)
  Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: setuptools>=68.2.2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pymorphy3>=1.0.0->ru-core-news-sm==3.8.0) (72.1.0)
Downloading pymorphy3-2.0.6-py3-none-any.whl (53 kB)
Downloading dawg2_python-0.9.0-py3-none-any.whl (9.3 kB)
Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 5.4 MB/s eta 0:00:00 MB/s eta 0:00:01:02
Installing collected packages: pymorphy3-dicts-ru, dawg2-python, pymorphy3, ru-core-news-sm
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [ru-core-news-sm]3/4 [ru-core-news-sm]
Successfully installed dawg2-python-0.9.0 pymorphy3-2.0.6 pymorphy3-dicts-ru-2.4.417150.4580142 ru-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('ru_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
# Для извлечения заиспользуем PhraseMatcher из SpaCy.
# Он быстро работает на большом объеме данных


def get_spacy_matcher(nlp, skills_list):
    matcher = PhraseMatcher(nlp.vocab, attr="LOWER")
    patterns = [nlp.make_doc(skill) for skill in skills_list]
    matcher.add("SKILL", patterns)
    return matcher

def extract_skills_from_doc(doc, matcher):
    seen = set()
    out = []
    for _match_id, start, end in matcher(doc):
        key = (start, end)
        if key in seen:
            continue
        seen.add(key)
        out.append(doc[start:end].text.strip())

    return out


nlp = spacy.load("ru_core_news_sm")


def get_skills_list(skills):
    # skills — это DataFrame; в матчер нужен список строк из колонки «Название»
    s = skills["Название"].dropna().astype(str).str.strip()
    return s.unique().tolist()

skills_list = get_skills_list(skills)
matcher = get_spacy_matcher(nlp, skills_list)

def extract_skills_text(text):
    if not isinstance(text, str) or not text.strip():
        return []
    doc = nlp(text)
    return extract_skills_from_doc(doc, matcher)

In [ ]:
# применяем 

df["skills_matched"] = df["short_description"].fillna("").map(extract_skills_text)

df

/var/folders/v8/lqntntc15fgctlxw4wdhwhx80000gn/T/ipykernel_33751/3357000340.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["skills_matched"] = df["short_description"].fillna("").map(extract_skills_text)

,title,hh_link,address,company,short_description,experience,salary,experience_min_years,skills_matched
0,Разработчик,https://hh.ru/vacancy/131819443?query=%D1%80%D...,Москва,"Русская Медиагруппа, радиохолдинг",Опыт работы,Опыт 3-6 лет,NaN,3.0,[]
1,Разработчик,https://hh.ru/vacancy/131986214?query=%D1%80%D...,Москва,Детский хоспис Дом с маяком,"Уверенное знание Python 3, базовых принципов О...",Опыт 1-3 года,"от 95 000 ₽ за месяц, на руки",1.0,"[знание, Python, Понимание, данных, SQL, JSON,..."
2,Backend-разработчик,https://hh.ru/vacancy/131274910?query=%D1%80%D...,Москва,ООО ГК СтиС,2+ года коммерческой разработки на PHP 7.4+. У...,Опыт 1-3 года,NaN,1.0,"[PHP, PHP 7.4, PHP 7.4+, Laravel, Laravel 7, E..."
3,Разработчик ЦФТ,https://hh.ru/vacancy/132003073?query=%D1%80%D...,Москва,Bell Integrator,Опыт работы с АБС «ЦФТ-Банк» в качестве,Опыт 3-6 лет,NaN,3.0,"[АБС, ЦФТ, ЦФТ-Банк, Банк]"
4,Разработчик C++,https://hh.ru/vacancy/132001730?query=%D1%80%D...,Москва,ООО БУЛАТ,Опыт разработки или исправления/доработки внут...,Опыт 3-6 лет,NaN,3.0,"[Linux, Kernel, Linux, оптимизация]"
...,...,...,...,...,...,...,...,...,...
13546,Бизнес-аналитик / Системный аналитик (Fullstac...,https://hh.ru/vacancy/131129287?query=%D0%BF%D...,Санкт-Петербург,ООО Апартмент системс,Опыт работы бизнес-аналитиком / системным анал...,Опыт 3-6 лет,NaN,3.0,"[бизнес, IT]"
13547,Девелопер обуви и аксессуаров,https://hh.ru/vacancy/131335836?query=%D0%BF%D...,"Москва, р-н Преображенское",Ushatava,"Аналогичный опыт работы от 3 лет, опыт работы",Опыт 1-3 года,NaN,1.0,[]
13548,Product Analyst,https://hh.ru/vacancy/131303603?query=%D0%BF%D...,"Москва, р-н Раменки",Clear Mind,Опытом самостоятельного создания воронок и фор...,Опыт 3-6 лет,NaN,3.0,"[web, SQL, Python, pandas, numpy, matplotlib]"
13549,Начальник отдела маркетинга,https://hh.ru/vacancy/128851476?query=%D0%BF%D...,"Челябинск, р-н Центральный",ООО Чебаркульская птица,"Опыт работы в маркетинге от 3 лет, из них не м...",Опыт 3-6 лет,NaN,3.0,[]
13550,Продуктовый маркетолог,https://hh.ru/vacancy/131156374?query=%D0%BF%D...,Москва,"""МТС"", Маркетинг и PR","Опыт работы с CJ, вовлекающими механиками, ист...",Опыт 3-6 лет,NaN,3.0,[]